name: 'Auto assign pull request to author'
description: 'Auto assign pull request to author'
icon: 'at-sign'
jobs:
  assign-pr-to-author:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('./scripts/assign-pr-to-author.js')
            await script({github, context, core})
